### ISSUE TITLE
UI not loading with large database 

### ISSUE THREAD

**Issue by bwoodworth** [LINKIWI/orion-server#15]
Firstly, thanks for this project. It is really really great looking way to see my location history.

I decided to import my location history from Google so I could see some past history. I wrote a simple script to get the data into a Mariadb database and ended up with about 2.5 million records. When I try to view even a short time period in the UI, it fails to load. Is this a limitation with the software or is there something I can do to fix the performance?

**Comment by LINKIWI** [comment]
Is it a web/UI issue or a server issue? If the former, the web UI isn't very performant when loading more than a few thousand points, regardless of the time interval. If the latter, try creating an index on the `timestamp` column. I just checked and my instance has 2.38M rows, and I haven't had any issues in querying 24 hour time ranges returning a couple hundred or so locations, though it does take a few seconds to complete.

**Comment by bwoodworth** [comment]
Thanks.  That helped with the server side.  I was trying to query a month of data and I have anywhere from 10k-20k records for any 30 day span.  It still works, but the UI side is pretty slow to load it up and is not responsive during the load.  Maybe that is just too much data for it to handle.  Would it be possible to load the data points asynchronously so the UI is still usable while all the points are loading?

**Comment by LINKIWI** [comment]
It's a performance limitation in the mapping library, unfortunately it's just not very fast when it needs to render thousands of points.

**Comment by bwoodworth** [comment]
Thanks.  Maybe I will pair down the database a bit to strip out unnecessary records.
