### ISSUE TITLE
Error when inserting new row into location table

### ISSUE THREAD

**Issue by luciano-fiandesio** [LINKIWI/orion-server#4]
When I push a new location from OwnTrack (android) I get this error in the Apache2 log:

`(_mysql_exceptions.OperationalError) (1054, "Unknown column 'address' in 'field list'") [SQL: u'INSERT INTO location (timestamp, user, device, latitude, longitude, accuracy, battery, `trigger`, connection, tracker_id, address) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (1517821639, 'orion', 'huaweip10p', 52.5360066, 13.4232977, 20, 13, None, 'm', '01', None)]`

I have installed Orion a couple of months ago and I have recently updated it (`git pull`). It looks like a new colum was added "address" linked to the reverse geocoding feature - which I haven't enabled yet.
The command `make init-db` doesn't seem to add this column to an existing database.

For the time being, I have fixed the error by manually adding the missing column:

`ALTER TABLE location ADD address varchar(4000);`

**Comment by LINKIWI** [comment]
Yep! The schema was modified to accommodate a new feature I needed, and the correct migration strategy is to alter the table schema exactly as you have done.
