### ISSUE TITLE
Friends support?

### ISSUE THREAD

**Issue by Narkhelek** [LINKIWI/orion-server#7]
This is an awesome replacement for recorder.  I did want to confirm that orion-server does not support the friends option where by the server returns a JSON payload back to the POSTing client with location information of friend Owntrack clients.  I didn't see any mention of this functionality and my deployment of orion-server does not.  Thanks!

**Comment by LINKIWI** [comment]
Correct, Orion does not support any functionality outside of simply reporting locations, which includes the friends feature.
