### ISSUE TITLE
Feature Request: Reporting from other apps

### ISSUE THREAD

**Issue by brianclemens** [LINKIWI/orion-server#8]
Would it be feasible to get this working with applications like:
* [μlogger](https://github.com/bfabiszewski/ulogger-android)
* [gpslogger](https://github.com/mendhak/gpslogger)
* [traccar](https://github.com/traccar/traccar-client-android)
Or some other app I haven't heard of?  Currently, the OwnTracks app refuses to work without Google Play Services (for functionality that should be optional but can't be disabled anyways).

**Comment by LINKIWI** [comment]
Sure, though the responsibility of conforming to the expected API lies innthe client. You'll have to fork one of those clients and modify the outgoing server request so that itnhas the same shape as the OwnTracks payload, and Orion will process it without error.

**Comment by snauth** [comment]
Gpslogger provides the custom url reporting method; works reliably with orion server in my setup.
